[package]
name = "argdown-tools"
version.workspace = true
edition.workspace = true

[features]
schemars = ["dep:schemars"]

[dependencies]
argdown-core = { workspace = true }
argdown-parser = { workspace = true }
argdown-model = { workspace = true }
serde = { workspace = true }
schemars = { version = "1.2.1", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
serde_json = { workspace = true }
