/**
 * Shared input schema + dispatch routing for both MCP tools
 * (`argdown_parse_inline` and `argdown_parse_file`).
 *
 * Zod-shape decision
 * ------------------
 * The MCP SDK's `McpServer.registerTool` accepts `inputSchema` typed as
 * `ZodRawShapeCompat | AnySchema`. `AnySchema = z3.ZodTypeAny | z4.$ZodType`
 * (see `@modelcontextprotocol/sdk/dist/esm/server/zod-compat.d.ts`), and the
 * SDK normalises whatever it receives via `normalizeObjectSchema` before
 * validating tool calls.
 *
 * A `z.discriminatedUnion(...)` is a `ZodTypeAny`, so it is directly assignable
 * to `inputSchema` — no `z.object({ payload: ... })` wrapping required and no
 * `zod-to-json-schema` conversion needed. Task 7's server code passes
 * `InputSchema` straight through:
 *
 *   server.registerTool("argdown_parse_inline", {
 *     description: "...",
 *     inputSchema: InputSchema,
 *   }, async (input) => dispatch(input, "parse"));
 *
 * The trade-off: the model-facing JSON schema is generated by the SDK from
 * the discriminated union, which produces a `oneOf` (or `anyOf`) at the top
 * level rather than an object with properties. That is the *correct* shape
 * for this tool — callers genuinely pass either `{ kind: "inline", source }`
 * or `{ kind: "file", path }`, never both — and surfacing that disjointness
 * to the model is desirable.
 *
 * Field descriptions are attached to the data-carrying fields (`source`,
 * `path`) rather than the `kind` literal, because the SDK does not surface
 * descriptions on union discriminators in a way models reliably consume.
 */

import { z } from "zod";
import { runInline } from "../argdown/inline.js";
import { runFile } from "../argdown/file.js";
import { shapeResponse, type ShapeMode, type McpToolResult } from "../shape.js";

export const InputSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("inline"),
    source: z
      .string()
      .min(1)
      .describe("Inline Argdown source string to parse."),
  }),
  z.object({
    kind: z.literal("file"),
    path: z
      .string()
      .min(1)
      .describe(
        "Filesystem path to a .argdown file. @import directives resolve relative to this file.",
      ),
  }),
]);

export type Input = z.infer<typeof InputSchema>;

export async function dispatch(
  input: Input,
  mode: ShapeMode,
): Promise<McpToolResult> {
  const withJson = mode === "export_json";

  try {
    const response =
      input.kind === "inline"
        ? runInline(input.source, { withJson })
        : await runFile(input.path, { withJson });
    return shapeResponse(response, mode);
  } catch (err) {
    // Defensive: runInline/runFile use `throwExceptions: false` and project
    // plugin errors into `response.exceptions`, so they should not throw
    // across this boundary. If something catastrophic *does* escape (e.g. a
    // plugin failure outside the Argdown error path), surface it as an MCP
    // tool error rather than letting it propagate to the transport layer.
    return {
      isError: true,
      content: [
        {
          type: "text",
          text: `Internal error: ${err instanceof Error ? err.message : String(err)}`,
        },
      ],
    };
  }
}
